### ISSUE TITLE
Support for d100

### ISSUE THREAD

**Issue by apetina** [reonZ/fast-rolls#1]
As simple as it sounds: possibility to roll d100 with one click

**Comment by reonZ** [comment]
To be completely honest with you, i just didn't want to create my own image for the d100, so i didn't add it, but it is something that will happen.

**Comment by apetina** [comment]
Just a suggestion, 2 overlapping d10 is the solution

**Comment by reonZ** [comment]
version 1.1.0 now use custom images and handles d100
