### ISSUE TITLE
Feature Request: maintain vertical size of buttons when scaling horizontally

### ISSUE THREAD

**Issue by esheyw** [reonZ/fast-rolls#2]
I was hoping to use this as a lightweight replacement for [Dice Tray](https://gitlab.com/asacolips-projects/foundry-mods/foundry-vtt-dice-calculator/), but unfortunately your buttons suffer from the same thing as theirs when using Sidebar Resizer: 
https://i.imgur.com/eygpRCD.gif
now DT has some buttons with the desired behaviour, see the bottom row here:
https://i.imgur.com/d9vI1Gs.gif
I have an issue on their github, but no movement in 9 months. I am in no way familiar enough with CSS to know what they're doing on the bottom row vs the others, but since I know it *can* be done, figured I'd ask if you could figure it out 🙂 I normally have my sidebar ~1.75x the width of normal, and so I've had to keep the actual tray part of DT turned off, because that is just too much vertical space for dice buttons. 

In fact, as an issue stretch goal: an alternate 'flat' mode that just has text `dX` button labels but is only ~1/3 as tall as current would be my ideal. But just having them not get taller than default would be a great improvement.

**Comment by reonZ** [comment]
The dice will no longer scale up when the sidebar width increases with version `1.1.2`
Let me know if this works with your use case.

**Comment by esheyw** [comment]
Yep that'll do. I had been thinking horizontal-only expansion, but keeping the size pinned and centering probably looks better, now that I'm playing with it. Thanks!
